---
title: "new_report2"
author: "Damian Ke & Kyriakos Papadopoulos"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(gridExtra)
library(ggplot2)
for (m_values in 2:4){
  set.seed(1234567890)
  max_it <- 100 # max number of EM iterations
  min_change <- 0.1 # min change in log lik between two consecutive iterations
  n=1000 # number of training points
  D=10 # number of dimensions
  x <- matrix(nrow=n, ncol=D) # training data
  true_pi <- vector(length = 3) # true mixing coefficients
  true_mu <- matrix(nrow=3, ncol=D) # true conditional distributions
  true_pi=c(1/3, 1/3, 1/3)
  true_mu[1,]=c(0.5,0.6,0.4,0.7,0.3,0.8,0.2,0.9,0.1,1)
  true_mu[2,]=c(0.5,0.4,0.6,0.3,0.7,0.2,0.8,0.1,0.9,0)
  true_mu[3,]=c(0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5)
  # plot(true_mu[1,], type="o", col="blue", ylim=c(0,1))
  # points(true_mu[2,], type="o", col="red")
  # points(true_mu[3,], type="o", col="green")
  # Producing the training data
  for(i in 1:n) {
    m <- sample(1:3,1,prob=true_pi)
    for(d in 1:D) {
      x[i,d] <- rbinom(1,1,true_mu[m,d])
    }
  }
  M=m_values # number of clusters
  w <- matrix(nrow=n, ncol=M) # weights
  pi <- vector(length = M) # mixing coefficients
  mu <- matrix(nrow=M, ncol=D) # conditional distributions
  llik <- vector(length = max_it) # log likelihood of the EM iterations
  # Random initialization of the parameters
  pi <- runif(M,0.49,0.51)
  pi <- pi / sum(pi)
  for(m in 1:M) {
    mu[m,] <- runif(D,0.49,0.51)
  }
  pi
  mu

  for(it in 1:max_it) {
    Sys.sleep(0.5)
    # E-step: Computation of the weights
    for (N in 1:n){
      px = c()
      for (m in 1:M){
        bern = 1
        for (d in 1:D){
          bern = bern * (mu[m,d]**x[N,d])*((1-mu[m,d])**(1-x[N,d]))
        }
        px[m]= (pi[m] * bern)
      }
      for (m in 1:M){
        w[N,m] = px[m]/sum(px) 
      }
    }
    #Log likelihood computation.
    difference = 0
    for (N in 1:n){
      logpx = c()
      for (m in 1:M){
        logbern = 0
        for (d in 1:D){
          logbern = logbern + x[N,d]*log(mu[m,d])+(1-x[N,d])*log(1-mu[m,d])
        }
        logpx[m]= log(pi[m]) + logbern
        difference = difference + w[N,m]*logpx[m]
      }
    }
    llik[it] = difference
    #cat("iteration: ", it, "log likelihood: ", llik[it], "\n")
    #flush.console()
    # Stop if the lok likelihood has not changed significantly
    if(it > 1){
      if(abs(llik[it] - llik[it - 1]) <= 0.1){
        break
      }
    }
    #M-step: ML parameter estimation from the data and weights
    mu <- t(w) %*% x/colSums(w)
    # Pi calulcation
    pi <- colSums(w) / nrow(x)
  }
  
  if(M==2){
    df_mu = data.frame(mu[1,],mu[2,],1:D)
    df_llik = data.frame(1:it,llik[1:it])
    colnames(df_mu) =c("mu_1","mu_2","Dimensions")
    colnames(df_llik) = c("Iterations","llik_iterations")
    p_1 = ggplot(df_mu, aes(x=Dimensions))+
      geom_line(aes(y=mu_1),color="red")+
      geom_line(aes(y=mu_2),color="blue")+
      ylab("Mu")+ggtitle("Mu for M=2")
    
    pl_1 = ggplot(df_llik, aes(x=Iterations))+
      geom_line(aes(y=llik_iterations))+
      ylab("Loglikelihood")+ggtitle("Loglikelihood for M=2")
  }
  else if(M==3){
    df_mu = data.frame(mu[1,],mu[2,],mu[3,],1:D)
    df_llik = data.frame(1:it,llik[1:it])
    colnames(df_mu) =c("mu_1","mu_2","mu_3","Dimensions")
    colnames(df_llik) = c("Iterations","llik_iterations")
    p_2 = ggplot(df_mu, aes(x=Dimensions))+
      geom_line(aes(y=mu_1),color="red")+
      geom_line(aes(y=mu_2),color="blue")+
      geom_line(aes(y=mu_3))+
      ylab("Mu")+ggtitle("Mu for M=3")
    
    pl_2 = ggplot(df_llik, aes(x=Iterations))+
      geom_line(aes(y=llik_iterations))+
      ylab("Loglikelihood")+ggtitle("Loglikelihood for M=3")
    
  }
  else if(M==4){
    df_mu = data.frame(mu[1,],mu[2,],mu[3,],mu[4,],1:D)
    df_llik = data.frame(1:it,llik[1:it])
    colnames(df_mu) =c("mu_1","mu_2","mu_3","mu_4","Dimensions")
    colnames(df_llik) = c("Iterations","llik_iterations")
    p_3 = ggplot(df_mu, aes(x=Dimensions))+
      geom_line(aes(y=mu_1),color="red")+
      geom_line(aes(y=mu_2),color="blue")+
      geom_line(aes(y=mu_3))+
      geom_line(aes(y=mu_4),color="cyan")+
      ylab("Mu")+ggtitle("Mu for M=4")
    
    pl_3 = ggplot(df_llik, aes(x=Iterations))+
      geom_line(aes(y=llik_iterations))+
      ylab("Loglikelihood")+ggtitle("Loglikelihood for M=4")
    
  }
}
grid.arrange(p_1, p_2,p_3, ncol=3)
grid.arrange(pl_1, pl_2,pl_3, ncol=3)
```

